version: '3.8'

services:
  frontend:
    build:
     context: ./frontend
     dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  flask-app:
    build: .
    ports:
      - "${FLASK_PORT}:5000"
    restart: always
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment: 
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - postgres-data:/var/lib/postgresql/data

  test:
    build: .
    command: pytest tests/
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - ./monitoring/loki-data:/var/loki
    restart: unless-stopped


volumes:
  postgres-data:

