name: CI - Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tomabucur/flask-docker-app:latest

      - name: Run fake test
        run: echo "Running tests..." && echo "All tests passed!"

      - name: Deploy to Ubuntu device
        run: |
          docker pull tomabucur/flask-docker-app:latest
          docker stop flask_app || true
          docker rm flask_app || true
          docker run -d --restart always --name flask_app -p 5000:5000 tomabucur/flask-docker-app:latest
