name: CI - Build, Test, Push, Deploy

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  build-test-deploy:
    runs-on: self-hosted
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          docker-compose run --rm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tomabucur/flask-docker-app:latest

      - name: Deploy to environment
        if: github.ref_name == 'dev' || github.ref_name == 'staging' || github.ref_name == 'main'
        run: |
          docker-compose -f docker-compose.yml down --remove-orphans
          docker-compose -f docker-compose.yml up -d --build
