name: CI - Build, Push, Deploy

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  build-push-deploy:
    runs-on: self-hosted

    environment: ${{ github.ref_name }}  # 👈 this dynamically uses the branch name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tomabucur/flask-docker-app:latest

      - name: Deploy with docker-compose
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d --build
