name: Tag on main push

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "Latest tag: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_tag
        run: |
          old_tag=${{ steps.get_tag.outputs.tag }}
          if [[ "$old_tag" == "" ]]; then
            new_tag="v1.0.0"
          else
            IFS='.' read -r major minor patch <<< "${old_tag#v}"
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}
