name: Tag on main push

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "Latest tag: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_tag
        run: |
          old_tag="${{ steps.get_tag.outputs.tag }}"
          if [[ -z "$old_tag" ]]; then
            new_tag="v1.0.0"
          else
            IFS='.' read -r major minor patch <<< "${old_tag#v}"
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Push tag to repository
        env:
          PAT: ${{ secrets.ACCESS_WORKFLOW_AND_REPO }}
          TAG: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag $TAG
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} $TAG

