name: Tag on main push

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "Latest tag: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_tag
        run: |
          old_tag=${{ steps.get_tag.outputs.tag }}
          if [[ "$old_tag" == "" ]]; then
            new_tag="v1.0.0"
          else
            IFS='.' read -r major minor patch <<< "${old_tag#v}"
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          fi
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Push tag to repository
        env:
          GIT_TOKEN: ${{ secrets.zen-access }}
          VERSION: ${{ env.VERSION }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/${{ github.repository }}
          git tag $VERSION
          git push origin $VERSION

